name: Release (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release target tag (e.g., v0.1.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as prerelease'
        required: false
        default: false
        type: boolean
      draft:
        description: 'Create as draft (no notifications)'
        required: false
        default: false
        type: boolean

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Package dist artifact
        run: |
          tar -czf dist.tar.gz dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
          generate_release_notes: true
          files: |
            dist.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
